apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zigflow.fullname" . }}
  labels:
    {{- include "zigflow.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "zigflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        # Prefill the Prometheus annotations. To activate, you will need to set:
        # prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{ .Values.service.metrics.port | quote }}
        {{- if .Values.workflow.enabled }}
        {{- if .Values.workflow.useInline }}
        checksum/workflow-inline: {{ .Values.workflow.inline | toYaml | b64enc | sha256sum | quote }}
        {{- end }}
        checksum/workflow-secret: {{ .Values.workflow.secret | sha256sum | quote }}
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "zigflow.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "zigflow.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          {{- if .Values.workflow.enabled }}
            - --file={{ .Values.workflow.file }}
          {{- end}}
          {{- range $key, $value := .Values.config }}
            - {{ printf "--%s=%v" $key $value | quote }}
          {{- end }}
          env:
            - name: HEALTH_LISTEN_ADDRESS
              value: {{ printf "0.0.0.0:%.0f" .Values.service.health.port | quote }}
            - name: METRICS_LISTEN_ADDRESS
              value: {{ printf "0.0.0.0:%.0f" .Values.service.metrics.port | quote }}
          {{- with .Values.envvars }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: health
              containerPort: {{ .Values.service.health.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.service.metrics.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.workflow.enabled .Values.volumes }}
          volumeMounts:
          {{- if .Values.workflow.enabled }}
            - mountPath: {{ .Values.workflow.file | quote }}
              subPath: workflow.yaml
              name: workflow
              readOnly: true
          {{- end }}
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
      {{- if or .Values.workflow.enabled .Values.volumes }}
      volumes:
      {{- if .Values.workflow.enabled }}
        - name: workflow
          secret:
            secretName: {{ .Values.workflow.secret }}
      {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
