services:
  # Set up a remote codec server to store in Redis
  codec:
    image: ghcr.io/mrsimonemms/temporal-codec-server/golang
    environment:
      BASIC_USERNAME: user
      BASIC_PASSWORD: password
      ENCRYPTION_TYPES: redis
      REDIS_URL: redis://redis:6379
    links:
      - redis

  redis:
    image: redis:alpine

  temporal:
    image: temporalio/temporal
    ports:
      - 8080:8233
    command: server start-dev --ip 0.0.0.0 --search-attribute Step=text
    healthcheck:
      test: ["CMD-SHELL", "temporal operator cluster health"]
      interval: 10s
      timeout: 10s
      retries: 3

  workflow: &trigger
    build:
      context: ../../
      target: builder
    environment:
      CODEC_ENDPOINT: http://codec:3000
      CODEC_HEADERS: '{"Authorization": "Basic dXNlcjpwYXNzd29yZA=="}'
      CONVERT_DATA: remote
      LOG_LEVEL: "${LOG_LEVEL:-debug}"
      TEMPORAL_ADDRESS: ${TEMPORAL_ADDRESS:-temporal:7233}
      TEMPORAL_NAMESPACE: ${TEMPORAL_NAMESPACE:-default}
      TEMPORAL_API_KEY: ${TEMPORAL_API_KEY:-}
      TEMPORAL_TLS: ${TEMPORAL_TLS:-false}
      WORKFLOW_FILE: ./examples/hello-world-encrypted-remote/workflow.yaml
    volumes:
      - ../../:/go/app
    command:
      - run
    links:
      - codec
      - temporal
    depends_on:
      temporal:
        condition: service_healthy

  trigger:
    <<: *trigger
    depends_on:
      workflow:
        condition: service_started
    working_dir: /go/app/examples/hello-world-encrypted-remote
    entrypoint: ""
    command:
      - go
      - run
      - .
